apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: monitor-sa
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: server
    #matchExpressions:
    #- {key: app, operator: In, values: [prometheus]}
    #- {key: component, operator: In, values: [server]}
  template:
    metadata:
      labels:
        app: prometheus
        component: server
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      nodeName: node01              #指定pod调度到哪个节点上
      serviceAccountName: monitor
      containers:
        - name: prometheus
          image: prom/prometheus:v2.2.1
          imagePullPolicy: IfNotPresent
          command:
            - prometheuste
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus        #数据存储目录
            - --storage.tsdb.retention=720h          #数据保存时长
            - --web.enable-lifecycle                 #开启热加载
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              subPath: prometheus.yml
            - mountPath: /prometheus/
              name: prometheus-storage-volume
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
                mode: 0644
        - name: prometheus-storage-volume
          hostPath:
            path: /data
            type: Directory

  kubectl apply -f prometheus-deploy.yaml

  kubectl get pods -o wide -n monitor-sa